FROM ubuntu:16.04
ENV DEBIAN_FRONTEND=noninteractive


# install dependency
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libssl-dev \
    uuid-dev \
    libgpgme11-dev \
    squashfs-tools \
    libseccomp-dev \
    wget \
    pkg-config \
    git \
    cryptsetup

# install go
ENV VERSION=1.16 OS=linux ARCH=amd64
RUN wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
    tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && \
    rm go$VERSION.$OS-$ARCH.tar.gz
ENV PATH="${PATH}:/usr/local/go/bin"

# install singularity of 3.6.4
RUN wget https://github.com/apptainer/singularity/releases/download/v3.6.4/singularity-3.6.4.tar.gz && \
    tar -xvf singularity-3.6.4.tar.gz && \
    rm singularity-3.6.4.tar.gz && \
    cd singularity && \
    ./mconfig && \
    make -C builddir && \
    make -C builddir install
